
INSERT INTO auth.users (id, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, aud, role)
VALUES (
    gen_random_uuid(),
    'admin@gmail.com',
    crypt('admin123', gen_salt('bf')),
    now(),
    '{"provider":"email","providers":["email"]}',
    '{}',
    'authenticated',
    'authenticated'
) ON CONFLICT (email) DO NOTHING;


CREATE TABLE IF NOT EXISTS public.profiles (
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    email TEXT,
    full_name TEXT,
    role TEXT
);


CREATE TABLE IF NOT EXISTS public.user_settings (
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    user_settings JSONB DEFAULT '{
        "status": true,
        "Actions": true,
        "AddShipment": true,
        "EstimatedTime": true,
        "News": true,
        "Report": true,
        "Archives": true
    }'::jsonb
);

CREATE TABLE IF NOT EXISTS public.shipments (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT now(),
    time DATE, 
    mmsi TEXT,
    bol TEXT,
    is_archived BOOLEAN DEFAULT false
);


INSERT INTO public.profiles (user_id, email, full_name, role)
SELECT id, email, 'admin', 'admin' FROM auth.users WHERE email = 'admin@gmail.com'
ON CONFLICT (user_id) DO NOTHING;

INSERT INTO public.user_settings (user_id)
SELECT id FROM auth.users WHERE email = 'admin@gmail.com'
ON CONFLICT (user_id) DO NOTHING;


ALTER TABLE public.profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.shipments DISABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.profiles TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.user_settings TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.shipments TO anon, authenticated, service_role;
